server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;

  location ~* ^/react/(static|favicon\.ico|logo192\.png|logo512\.png|manifest\.json|robots\.txt) {
    try_files $uri =404;
    access_log off;
    expires 1y;
    add_header Cache-Control "public";
  }

  location /react {
    try_files $uri /react/index.html;
  }

  error_page 500 502 503 504 /50x.html;
  location = /50x.html {
    root /usr/share/nginx/html;
  }
}